import type { NextPage } from "next";
import Head from "next/head";
import DashboardLayout from "../layouts/Dashboard";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Hustle Sasa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-red-500">
        <DashboardLayout>
          <div>sskjdn</div>
        </DashboardLayout>
      </main>
    </div>
  );
};

export default Home;
