import type { NextPage } from "next";
import Head from "next/head";
import DashboardLayout from "../layouts/Dashboard";
import ShopLayout from "../layouts/Shop";
import { Filters } from "../components/Filters";
import ShopList from "../components/ShopList";
import { FilterProvider } from "../contexts/FilterContext";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Hustle Sasa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <FilterProvider>
          <DashboardLayout>
            <ShopLayout>
              <Filters />
              <ShopList />
            </ShopLayout>
          </DashboardLayout>
        </FilterProvider>
      </main>
    </div>
  );
};

export default Home;
